-- Revelation (19720) "The Dreadnought cannot be fitted" fix.
-- Root cause: effect 1626 (dreadnoughtShipBonusLaserCapNeedA1) referenced
-- preExpression 6466 / postExpression 6467 which did NOT exist in dgmExpressions.
-- When the client hit "Make Ship Active", StartPassiveEffects tried to load the
-- expression tree for passive effect 1626, the missing expression IDs made the
-- client's start fail -> FitItemToLocation -> UserError('ModuleFitFailed')
-- -> "The Dreadnought cannot be fitted." (only Revelation; other dreadnoughts
-- had valid expression trees for their bonus effects).
--
-- Fix: build a valid expression tree for 1626 mirroring the working 1627
-- (dreadnoughtShipBonusLaserRofA2) tree but targeting capacitorNeed (attr 6)
-- instead of speed (attr 51) on X-Large Energy Turret modules.
--
-- +migrate Up
INSERT INTO dgmExpressions (expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID)
VALUES (19279, 22, 0, 0, '', 'capacitorNeed attribute constant for dreadnoughtShipBonusLaserCapNeedA1', 'capacitorNeed', 0, 0, 6)
ON DUPLICATE KEY UPDATE expressionAttributeID = 6;

INSERT INTO dgmExpressions (expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID)
VALUES (19280, 12, 6007, 19279, '', 'Autogenerated ATT, 6 on modules requiring X-Large Energy Turret on Ship', 'CurrentShip[X-Large Energy Turret]->capacitorNeed', 0, 0, 0)
ON DUPLICATE KEY UPDATE operandID = 12, arg1 = 6007, arg2 = 19279;

INSERT INTO dgmExpressions (expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID)
VALUES (19281, 31, 1095, 19280, '', 'Autogenerated EFF, PostPercent modification to 6 on modules requiring X-Large Energy Turret on Ship', '(CurrentShip[X-Large Energy Turret]->capacitorNeed).(PostPercent)', 0, 0, 0)
ON DUPLICATE KEY UPDATE operandID = 31, arg1 = 1095, arg2 = 19280;

INSERT INTO dgmExpressions (expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID)
VALUES (19282, 9, 19281, 6422, '', 'ALRSM for dreadnoughtShipBonusLaserCapNeedA1', '((CurrentShip[X-Large Energy Turret]->capacitorNeed).(PostPercent)).ALRSM(dreadnoughtShipBonusA1)', 0, 0, 0)
ON DUPLICATE KEY UPDATE operandID = 9, arg1 = 19281, arg2 = 6422;

INSERT INTO dgmExpressions (expressionID, operandID, arg1, arg2, expressionValue, description, expressionName, expressionTypeID, expressionGroupID, expressionAttributeID)
VALUES (19283, 61, 19281, 6422, '', 'RLRSM for dreadnoughtShipBonusLaserCapNeedA1', '((CurrentShip[X-Large Energy Turret]->capacitorNeed).(PostPercent)).RLRSM(dreadnoughtShipBonusA1)', 0, 0, 0)
ON DUPLICATE KEY UPDATE operandID = 61, arg1 = 19281, arg2 = 6422;

UPDATE dgmEffects SET preExpression = 19282, postExpression = 19283 WHERE effectID = 1626;
UPDATE dgmEffects SET preExpression = 6469, postExpression = 6470 WHERE effectID = 1627;

-- +migrate Down
DELETE FROM dgmExpressions WHERE expressionID IN (19279, 19280, 19281, 19282, 19283);
UPDATE dgmEffects SET preExpression = 0, postExpression = 0 WHERE effectID = 1626;
UPDATE dgmEffects SET preExpression = 6469, postExpression = 6470 WHERE effectID = 1627;