-- +migrate Up
-- Bot smalltalk lines moved out of hardcoded arrays into a table, so the pool
-- can grow at runtime: BuildBotSmalltalkLine reads lines from here (prefer the
-- least-used ones) and BotMgr::ExpandSmalltalkPool asks DeepSeek for new lines
-- every 30 min.  profession = PlayerBot::BotProfession (0 hunter .. 8
-- industrialist); 255 = the separate "under attack" combat pool.
CREATE TABLE botSmalltalk (
    id        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    profession TINYINT UNSIGNED NOT NULL DEFAULT 255,
    line      VARCHAR(255) NOT NULL,
    uses      INT UNSIGNED NOT NULL DEFAULT 0,
    lastUse   DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_line (line),
    KEY ix_prof (profession, uses)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO botSmalltalk (profession, line) VALUES
-- hunter (0)
(0,'anyone in %s worth engaging?'),
(0,'scan shows a target, thinking about it.'),
(0,'this gate''s quiet, might camp a bit.'),
(0,'gf if anyone''s up for a scrap.'),
(0,'d-scan shows something, holding here.'),
(0,'neuts and scram ready, just need a volunteer.'),
(0,'local''s getting spicy, staying aligned.'),
(0,'pods are worth more than the ships, fyi.'),
(0,'who flies a mackinaw through %s solo...'),
(0,'sitting on the gate, counting blinks.'),
(0,'my killboard needs some love.'),
(0,'solo pvp or nothing, that''s the rule.'),
(0,'combat probes converge fast enough, patience.'),
(0,'if you''re flashing and slow, that''s on you.'),
(0,'checking the undefended nodes in %s.'),
(0,'catch of the day almost slipped the bubble.'),
-- rat hunter (1)
(1,'anoms are quiet in %s today.'),
(1,'just popped a nice rat spawn, wallet''s happy.'),
(1,'this system''s rats hit harder than the last one.'),
(1,'anyone seen a good haven around %s?'),
(1,'plex paid out decent, faction spawn even.'),
(1,'rats dropped a nameplate module, score.'),
(1,'clearing anoms, don''t mind me.'),
(1,'haven in %s is up, farm it before it despawns.'),
(1,'bounties add up, that''s the grind.'),
(1,'escalation from the last site, fingers crossed.'),
(1,'nothing beats a clean ratting rotation.'),
(1,'sentry guns ate my drones, rude.'),
(1,'angled for the haven, anomalies first though.'),
(1,'back-to-back sites, isk printer mode.'),
(1,'those rat battleships tank forever without neuts on them.'),
(1,'checking %s for reds before I start the site.'),
-- miner (2)
(2,'belts in %s are quiet today, almost have the hold full.'),
(2,'strip miners humming, ore''s piling up nicely.'),
(2,'anyone know the refine rate at the station here?'),
(2,'this ore holds better than the last rock I mined.'),
(2,'haul full again, time for a station run.'),
(2,'a Mining Laser II would be nice, still on the T1 setup.'),
(2,'watch the %s belts, rats popped me early last time.'),
(2,'an ice belt would be nice, but ore pays the bills.'),
(2,'venture tried to bump me off the rock, cute.'),
(2,'half a hold of veldspar, nothing fancy today.'),
(2,'mining in a 0.5 is basically a spa day, come join %s.'),
(2,'ore bay says no more, docking up.'),
(2,'anyone buying minerals? got a fresh load.'),
(2,'rookie numbers on my ore hold but it adds up.'),
(2,'surveyor says this rock has a few more cycles in it.'),
(2,'the belt respawn in %s just got me a full spawn of rocks.'),
-- trader (3)
(3,'buy orders up in %s, spread''s nice.'),
(3,'market''s moving, good day to be a trader.'),
(3,'someone undercut me again, classic.'),
(3,'haul of goods just went out, profit''s in.'),
(3,'0.01 ISK wars are real in %s.'),
(3,'updated my orders, margins look fine.'),
(3,'regional prices are all over the place.'),
(3,'escrow''s heavy, thinking about a big buy.'),
(3,'the hub crowd keeps me honest on prices.'),
(3,'bought low, stacked it in the hangar.'),
(3,'station traders never sleep, huh.'),
(3,'skip the margins, volume is the play.'),
(3,'somebody bulk-bought the whole mineral stock, nice.'),
(3,'skill queue says Accounting, wallet says patience.'),
(3,'relisting orders in %s, taxes hurt though.'),
(3,'day trading in a station beats getting shot at.'),
-- courier (4)
(4,'courier job open to the hub if anyone''s hauling.'),
(4,'just moved a load through %s, easy isk.'),
(4,'anyone need something moved to Jita?'),
(4,'cargo''s in, contract''s up, rates are fair.'),
(4,'hauling day, slow but steady.'),
(4,'collateral''s steep but the reward covers it.'),
(4,'two more runs and I''m done for the day.'),
(4,'gate camps kept it spicy on the way in.'),
(4,'indy hulls are slow but they never die, mostly.'),
(4,'package delivered, signing the next one.'),
(4,'if you see a hauler in %s, be nice, it''s me.'),
(4,'the client wanted express delivery, done.'),
(4,'freight volume is up, good sign for trade.'),
(4,'one more load to move before downtime.'),
(4,'sticky cargo hatch almost cost me a package.'),
(4,'route through %s is quiet today.'),
-- hacker (5)
(5,'datacore prices better hold, I''ve got a hold full.'),
(5,'relic site in %s was worth the scan.'),
(5,'these data sites are getting camped lately.'),
(5,'found a nice relic, decryptors are mine now.'),
(5,'can opener time, cans are fragile this patch.'),
(5,'ghost site gave nothing, typical.'),
(5,'datacores round out the wallet nicely.'),
(5,'someone''s probes are sweeping %s, wrapping up.'),
(5,'relic cans were fake, just alloys. meh.'),
(5,'covert ops frigate life: scan, pop, vanish.'),
(5,'the local has reds, saving the cans for later.'),
(5,'exploration pays better than my old mining op.'),
(5,'hacked the can, got a skillbook I already know...'),
(5,'analyzers at II, no more fail cycles.'),
(5,'checking %s for sigs before I head out.'),
(5,'sites keep despawning on me, unlucky.'),
-- explorer (6)
(6,'found a sig in %s, scanning it down.'),
(6,'wormhole in here earlier, anyone peeked?'),
(6,'probes out, system''s got a few signatures.'),
(6,'that null static is tempting.'),
(6,'combat sigs first, data later.'),
(6,'scan deviations killing me today, need better skills.'),
(6,'found a wormhole, decided to skip it this time.'),
(6,'sig density in %s is actually decent.'),
(6,'probing with bookmarks is a lost art.'),
(6,'caught a gas site, not my thing though.'),
(6,'one more sig, then I''m heading home.'),
(6,'mapped %s, mostly quiet.'),
(6,'relays are cheap, scan results are not.'),
(6,'the debris of dead probes litters the system, lol.'),
(6,'uncovering sigs one ping at a time.'),
(6,'found a candidate, warping to check.'),
-- missioner (7)
(7,'agent mission in %s is a nice isk flow.'),
(7,'mission done, reporting back to the agent.'),
(7,'storyline missions pay oddly well.'),
(7,'running missions for the navy today.'),
(7,'the mission brief actually made me laugh.'),
(7,'declined a kill mission, ships too pricey.'),
(7,'missions keep %s lively.'),
(7,'lp store haul later, saved up enough.'),
(7,'another cleanup order from command, done.'),
(7,'report filed, next mission please.'),
-- industrialist (8)
(8,'POS build queue is full again.'),
(8,'new batch of modules fresh from the assembly array.'),
(8,'manufacturing margins got thin this week.'),
(8,'PI chains are running smooth in %s.'),
(8,'waiting on the reactor cycle, then it''s haul time.'),
(8,'somebody bought out my whole module stock, nice.'),
(8,'blueprints researched, production rescheduled.'),
(8,'industry alt life is calm, I recommend it.'),
(8,'silo''s full, couriers have work now.'),
(8,'t2 components soon, feedstock''s ready.'),
-- combat / under attack (255)
(255,'bit busy here, someone''s on me.'),
(255,'ffs, getting shot at in %s.'),
(255,'who''s engaging me??'),
(255,'tackled, need backup maybe.'),
(255,'warp scramble on me, hitting hard.'),
(255,'my tank won''t hold forever, help.'),
(255,'armor''s dropping, might have to bug out.'),
(255,'entry damage was rough, still here though.'),
(255,'drones out, taking fire in %s.'),
(255,'neut pressure is real, cap''s dying.'),
(255,'they brought friends, this is uneven.'),
(255,'almost through it, tank''s holding. barely.');

-- +migrate Down
DROP TABLE IF EXISTS botSmalltalk;
